### ISSUE TITLE
Plans for Testflight SDK 1.2.4

### ISSUE THREAD

**Issue by ygbr** [viezel/NappTestFlight#1]
Hi Mads,

Any plans for updating the Ti Module with the latest version of Testflight SDK? Do you think that if I just replace the SDK and recompile the module it will work?

It seems that some things have changed since 1.1 like setOptions and setDeveiceIdentifier... but not sure yet if they would impact the module itself...

https://testflightapp.com/sdk/release_notes/1.2.4/

Thanks.

**Comment by viezel** [comment]
yeah, I should do that.. 
ill look into it when I have time. But if you want it pick, you could do a PR.

**Comment by viezel** [comment]
I just updated it. works for you?
