### ISSUE TITLE
Update iOS SDK and add instructions for tracking

### ISSUE THREAD

**Issue by FokkeZB** [viezel/NappTestFlight#10]
If you would like to have your testers' sessions identified and allow In App Updates: make sure you are using SDK 2.2.0 or later, remove the "iTunesArtwork" file from your build, and re-upload.

See https://www.testflightapp.com/sdk/ios/doc/

**Comment by jonatansberg** [comment]
@FokkeZB Why do you need to remove the iTunesArtwork? I can't find anything regarding that in the docs..

I just updated the SDK to 2.2.1 and everything seems to be working.

**Comment by FokkeZB** [comment]
I have no clue why I put that there really...

**Comment by jonatansberg** [comment]
Haha, okay then, I'll submit a pull request.

**Comment by viezel** [comment]
#12 closes this.
