### ISSUE TITLE
SDK 3.0.0

### ISSUE THREAD

**Issue by caspahouzer** [viezel/NappTestFlight#14]
TestFlight releases SDK 3.0.0

Could you please update your module?

**Comment by FokkeZB** [comment]
... and drop the Android one? :(

**Comment by caspahouzer** [comment]
Why?

**Comment by FokkeZB** [comment]
Heard they will drop Android support in March

**Comment by caspahouzer** [comment]
True!
https://www.testflightapp.com/sdk/android/download/

Like they dropped FlightPath.

Maybe it's time to move to an alternate solution. But TestFlight has been great for now!

**Comment by FokkeZB** [comment]
https://www.installrapp.com looks promising for getting it to testers, but need something else for feedback and logs.

**Comment by caspahouzer** [comment]
http://www.appaloosa-store.com/
http://hockeyapp.net

But none for free. And installrapp.com is only for iOS. For me no problem, I only got iOS Apps.

Hopefully TestFlight just stays there. Even when it's only for iOS.

**Comment by ericboehs** [comment]
:+1: to updating to 3.0.0. I'd say dropping Android support would be in another issue though.

**Comment by productiveme** [comment]
+1 for updating to 3.0.0
