### ISSUE TITLE
Rejected by apple with "Non-public API usage: UDID"

### ISSUE THREAD

**Issue by killroyboy** [viezel/NappTestFlight#2]
The new restrictions from Apple that went into effect on May 1st caused problems with this module.  I had to just remove it from my project in order to submit to Apple. 

Hopefully simply upgrading the TestFlight SDK will solve the problem.

**Comment by viezel** [comment]
just updated the module.. solves your problem?

**Comment by killroyboy** [comment]
Yup.  Looks like that fixed it.  Thanks for the quick response!
