### ISSUE TITLE
Android module?

### ISSUE THREAD

**Issue by killroyboy** [viezel/NappTestFlight#4]
I tried using the android module and have not been successful.  I know it's in beta, but are there instructions for installing.  The jar file in the dist directory doesn't help by itself.  Copying the rest of the project into the module directory allows it to be detected, but build fails with the following:

[ERROR][TiApplication( 1549)](KrollRuntimeThread) [30,88] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: Couldn't load dk.napp.testflight: findLibrary returned null; Titanium 3.1.2,2013/08/14 12:46,5ceaff8
[ERROR][TiApplication( 1549)] java.lang.UnsatisfiedLinkError: Couldn't load dk.napp.testflight: findLibrary returned null
[ERROR][TiApplication( 1549)]   at java.lang.Runtime.loadLibrary(Runtime.java:365)
[ERROR][TiApplication( 1549)]   at java.lang.System.loadLibrary(System.java:535)
[ERROR][TiApplication( 1549)]   at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:114)
[ERROR][TiApplication( 1549)]   at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:81)
[ERROR][TiApplication( 1549)]   at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:175)
[ERROR][TiApplication( 1549)]   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

Any help would be appreciated!

**Comment by viezel** [comment]
hi, 
ive added a module zip in the dist folder: https://github.com/viezel/NappTestFlight/blob/master/android/dist/dk.napp.testflight-android-0.6.zip

**Comment by killroyboy** [comment]
Perfect!
