### ISSUE TITLE
Update to Testflight SDK 2.0

### ISSUE THREAD

**Issue by tylerlane** [viezel/NappTestFlight#5]
Can you please update your module to use SDK 2.0?

**Comment by viezel** [comment]
There you go :) 

https://github.com/viezel/NappTestFlight/blob/master/ios/dist/dk.napp.testflight-iphone-2.0.zip

**Comment by tylerlane** [comment]
Wonderful! Did they remove the launchFeedback option in 2.0? I can't launch
it and it don't see it in the source of your module.

Tyler Lane
tyler@nolongervalid.com

**Comment by tylerlane** [comment]
And thanks again for so quickly getting this updated!

Tyler Lane
tyler@nolongervalid.com

**Comment by viezel** [comment]
Yes, read the changelog in the testflight website

**Comment by tylerlane** [comment]
Yep got it! thanks again :)

Tyler Lane
tyler@nolongervalid.com
